### ISSUE TITLE
Keeps throwing invalid format error.

### ISSUE THREAD

**Issue by Suleman-Elahi** [rahulnpadalkar/Sheddit#1]
The documentation is a bit unclear. I tried posting the data in JSON format and in the simple text format...but not working for me....maybe I am missing something here.

![image](https://user-images.githubusercontent.com/24384996/78419533-6914cf00-7664-11ea-8704-cd273d66029f.png)

**Comment by rahulnpadalkar** [comment]
Valid JSON Format 

     ` "subreddits":"test", (In case multiple, comma seperate them)

      "title":"title-of-your-post",

      "link":"any-validurl",

      "text":"any text",

      "scheduledate":"2020-03-06T10:46:00.000Z" (ISO DatetimeString),

     "provider": "reddit" (can also be twitter)`
In case where provider is reddit link and text both cannot have values. In case of twitter link field will be ignored. Value in text field is tweeted.

**Comment by rahulnpadalkar** [comment]
I recommend using https://github.com/rahulnpadalkar/ShedditUI

**Comment by Suleman-Elahi** [comment]
Isn't this is a valid JSON format? it didn't work for me though....tried ShedditUI !
```
[
  {
    "subreddits": "learnpython",
    "title": "My first GUI application ",
    "link": "https://github.com/Suleman-Elahi/Covid19Status",
    "scheduledate": "2020-04-04T11:00:00.000Z"
  }
]
```

Also, the ShedditUI at localhost:8080 shows a blank page !!

![image](https://user-images.githubusercontent.com/24384996/78522857-62b15f00-77ec-11ea-8bf3-01888a53af0d.png)

**Comment by rahulnpadalkar** [comment]
It's an electron application, you need to run
`npm run electron:serve`

**Comment by rahulnpadalkar** [comment]
This is valid JSON, it has to be just one object  and not an array.
`
{
    "subreddits": "learnpython",

    "title": "My first GUI application ",

    "link": "https://github.com/Suleman-Elahi/Covid19Status",

    "scheduledate": "2020-04-04T11:00:00.000Z",

    "provider":"reddit"

  }
`

**Comment by Suleman-Elahi** [comment]
Thank you so much...the JSON part is sorted out and the app is also running. One last supid thing is what should I use for the server address in the UI. localhost:7009 and 127.0.0.1:7009 and http://localhost:7009 is not working...however the main issue I had is resolved.

![image](https://user-images.githubusercontent.com/24384996/78526455-a9f11d00-77f7-11ea-8d8f-7d75d53138cc.png)
![image](https://user-images.githubusercontent.com/24384996/78526464-aeb5d100-77f7-11ea-8d6d-fbdcf44ca2b0.png)

**Comment by rahulnpadalkar** [comment]
Try giving ip address of your machine and then the port number, localhost should work though.

**Comment by Suleman-Elahi** [comment]
No that doesn't work either even after appending http:// in the beginning
![image](https://user-images.githubusercontent.com/24384996/78526983-58499200-77f9-11ea-8c57-98b6157bdf6f.png)

**Comment by rahulnpadalkar** [comment]
I think the Sheddit Server isn't running have you cloned https://github.com/rahulnpadalkar/Sheddit?
ShedditUI is just the frontend. You need Sheddit server running for the UI to work.
After cloning you have to add an env file and then run

`godotenv -f .env go run main.go`

**Comment by Suleman-Elahi** [comment]
Sheddit is indeed running, I can even see the request in the logs...but not connecting somehow.
![image](https://user-images.githubusercontent.com/24384996/78527278-1705b200-77fa-11ea-88e4-6b4d3d1cf40a.png)

**Comment by rahulnpadalkar** [comment]
Looks like I haven't pushed the backend code for it. Thanks! Will do it asap.

**Comment by Suleman-Elahi** [comment]
That's okay,,,i just posting data via curl to schedule posts...for me, this is much easier. Btw add documentation for setting up Twitter keys and tokens too.
