### ISSUE TITLE
Interacting with the server

### ISSUE THREAD

**Issue by jamesthesken** [rahulnpadalkar/Sheddit#2]
Hey Rahul, thank you for putting this project together!

I had some trouble running the ShedditUI, everything built/ran but nothing showed up. Would it be possible to see some examples of interacting with the server **without** the desktop application?

I'm new to this level of golang development so forgive me if the question doesn't make sense.

**Comment by rahulnpadalkar** [comment]
Hi, thanks for checking out this project. 

ShedditUI needs Sheddit server to function. So make sure sheddit server is running. Also can you elaborate more on the problem. 

If you want to interact with the server directly, supported endpoints are documented at https://github.com/rahulnpadalkar/Sheddit#supported-endpoints also, i will be updating the readme soon to document all endpoints. 

You can find all supported endpoints in https://github.com/rahulnpadalkar/Sheddit/blob/master/requesthandler/server.go
